version: "3"

services:

  nodejs:
    build: ./nodejs/
    volumes:
       - ./nodejs/src:/usr/src/app
    ports:
      - "3000:8080"
    links:
      - neo4j

  neo4j:
    build: ./neo4j/
    volumes:
    - ./db/data:/data # provision the volumes
    - ./db/logs:/logs # provision the volumes
    ports:
    - "17474:7474" # meant for debugging into neo4j. can be removed
    - "17687:7687" # meant for debugging into neo4j. can be removed